[package]
name = "slack_status"
version = "1.0.0"
authors = ["Haim Gelfenbeyn <haim@g8n.me>"]
edition = "2018"

[dependencies]
config = "0.9"
docopt = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
slack_api = "0.21.0"
